# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [6]:
import numpy as np

print("Numpy version:", np.__version__)     #verifying import

Numpy version: 2.0.0


#### 2. Print the numpy version and the configuration (★☆☆)

In [8]:
import numpy as np

print("Numpy version:", np.__version__)        #verifying import
np.show_config()

Numpy version: 2.0.0
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30154",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.10",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30154",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.27",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-zh8sc4vi/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/includ

#### 3. Create a null vector of size 10 (★☆☆)

In [10]:

import numpy as np

null_vector = np.zeros(10)      #creating vector

print("Null vector of size 10:", null_vector)

Null vector of size 10: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [11]:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

#Finding the memory size of the array
memory_size = arr.size * arr.itemsize

print("Memory size of the array:", memory_size, "bytes")


Memory size of the array: 40 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [12]:
# Importing the numpy package
import numpy as np

help(np.add)


Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its or

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:

import numpy as np

null_vector = np.zeros(10)

#Setting the 5th element to 1
null_vector[4] = 1

print("Null vector of size 10 with 5th element as 1:", null_vector)


Null vector of size 10 with 5th element as 1: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [14]:

import numpy as np

#Creating a vector with values ranging from 10 to 49
vector = np.arange(10, 50)

print("Vector with values from 10 to 49:", vector)


Vector with values from 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [15]:

import numpy as np

vector = np.array([1, 2, 3, 4, 5])

#Reversing the vector
reversed_vector = vector[::-1]

print("Original vector:", vector)
print("Reversed vector:", reversed_vector)


Original vector: [1 2 3 4 5]
Reversed vector: [5 4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [18]:

import numpy as np

#reating a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)

print("3x3 matrix :")
print(matrix_3x3)


3x3 matrix :
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
#doubt (will get it cleared)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [16]:

import numpy as np

identity_matrix = np.eye(3)

print("3x3 Identity Matrix:")
print(identity_matrix)


3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [17]:

import numpy as np

#3x3 array with random values
random_array = np.random.rand(3, 3)

print("3x3 array with random values:")
print(random_array)


3x3 array with random values:
[[0.7869547  0.98705316 0.23380185]
 [0.09688546 0.73517414 0.85355541]
 [0.81639364 0.69518909 0.03083191]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [19]:

import numpy as np

#10x10 array with random values
random_array = np.random.rand(10, 10)

#Finding the minimum value in the array
min_value = random_array.min()

#Finding the maximum value in the array
max_value = random_array.max()

print("Random 10x10 array:")
print(random_array)
print("Minimum value in the array:", min_value)
print("Maximum value in the array:", max_value)


Random 10x10 array:
[[0.47448905 0.09890714 0.93549896 0.0457447  0.86362998 0.6860726
  0.15825591 0.62050563 0.03004405 0.70528533]
 [0.7840491  0.31738315 0.87455336 0.53109935 0.43324788 0.49525777
  0.32887413 0.44444791 0.97138262 0.25487902]
 [0.47365806 0.63264833 0.13075249 0.44180263 0.55208573 0.90832609
  0.54601864 0.69812355 0.43141811 0.56454883]
 [0.64498335 0.38555445 0.38161167 0.20348633 0.71816135 0.5010526
  0.5790224  0.13655238 0.05215389 0.61661377]
 [0.9026155  0.89424856 0.1123904  0.57707944 0.91136765 0.28356022
  0.07095888 0.33963847 0.57712145 0.23503163]
 [0.18594171 0.47087505 0.51631089 0.69826339 0.46188049 0.14738405
  0.70309284 0.05852735 0.30587737 0.07607061]
 [0.27812581 0.86868985 0.20658471 0.48782576 0.38887323 0.49489646
  0.52985988 0.36416177 0.20534027 0.07808426]
 [0.50551357 0.45594109 0.770637   0.52263111 0.95641192 0.74599288
  0.08274738 0.96511328 0.67305916 0.16755006]
 [0.25072684 0.82092267 0.3026339  0.35833007 0.96488259 0.627

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [20]:
import numpy as np

vector = np.arange(1, 31)

mean_value = np.meean(vector)

print("Mean value of the vector:", mean_value)


Mean value of the vector: 15.5


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
#doubt

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
#doubt

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [21]:

import numpy as np

#matrix with zeroes
matrix = np.zeros((5, 5), dtype=int)

for i in range(1, 5):
    matrix[i, i-1] = i

print("5x5 matrix with values just below the diagonal:")
print(matrix)


5x5 matrix with values just below the diagonal:
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [22]:
#used tiling

import numpy as np

checkerboard = np.tile([[0, 1], [1, 0]], (4, 4))

print("8x8 Checkerboard matrix:")
print(checkerboard)


8x8 Checkerboard matrix:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [24]:

import numpy as np

shape = (6, 7, 8)
array = np.zeros(shape)

#unreavel function
index = np.unravel_index(100, shape)

print("The index of the 100th element is:", index)


The index of the 100th element is: (np.int64(1), np.int64(5), np.int64(4))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
import numpy as np

checkerboard = np.tile([[0, 1], [1, 0]], (4, 4))

print("8x8 Checkerboard matrix:")
print(checkerboard)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [25]:

import numpy as np

matrix = np.random.rand(5, 5)

#finding min and max first 
min_value = matrix.min()
max_value = matrix.max()

#approach to normalixation
normalized_matrix = (matrix - min_value) / (max_value - min_value)

print("Original Matrix:\n", matrix)
print("\nNormalized Matrix:\n", normalized_matrix)


Original Matrix:
 [[0.9641858  0.6479153  0.49664785 0.75256825 0.03755577]
 [0.40211199 0.16617012 0.44946103 0.94652435 0.41669871]
 [0.66475757 0.86510239 0.76458152 0.77868094 0.1115555 ]
 [0.47196754 0.33857169 0.28995426 0.18756696 0.27235955]
 [0.40044446 0.26753873 0.3197356  0.84505476 0.65853986]]

Normalized Matrix:
 [[1.         0.65868741 0.4954427  0.7716267  0.        ]
 [0.39342154 0.13879795 0.44451965 0.98094013 0.40916323]
 [0.67686323 0.89307122 0.78459117 0.79980698 0.07985898]
 [0.46880821 0.32485017 0.27238324 0.16188898 0.2533954 ]
 [0.39162198 0.24819286 0.30452265 0.87143624 0.67015321]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
#doubt

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [26]:

import numpy as np

#5x3 matrix
matrix_5x3 = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9],
                       [10, 11, 12],
                       [13, 14, 15]])

#3x2 matrix
matrix_3x2 = np.array([[1, 2],
                       [3, 4],
                       [5, 6]])

# Multiplying
result = np.dot(matrix_5x3, matrix_3x2)

print("Result of multiplying a 5x3 matrix by a 3x2 matrix:")
print(result)


Result of multiplying a 5x3 matrix by a 3x2 matrix:
[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
#didn't understand logic (just negate the same value?)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
9
#range(5)returns [0, 1, 2, 3, 4].
#The sum function starts with an initial value of -1.
#So, -1 + 0 + 1 + 2 + 3 + 4 = 9

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

In [28]:

import numpy as np

float_array = np.array([1.2, -2.5, 3.7, -4.4])
# Rounding away from zero
rounded_array = np.ceil(float_array)  # Use np.floor for -ve nos

print("Original array:", float_array)
print("Rounded away from zero:", rounded_array)


Original array: [ 1.2 -2.5  3.7 -4.4]
Rounded away from zero: [ 2. -2.  4. -4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [33]:

import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

#findinhg common
common_values = np.intersect1d(array1, array2)

print("Common values between the two arrays:", common_values)


Common values between the two arrays: [4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
#didnt get the answer to #doubtr

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
#no, because one returns real and the other returns complex value

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [31]:

import numpy as np
from datetime import datetime, timedelta

#today's date
today = np.datetime64(datetime.now().date())

#yesterday's date
yesterday = today - np.timedelta64(1, 'D')

#tomorrow's date
tomorrow = today + np.timedelta64(1, 'D')

print("yesterady:", yesterday)
print("today:", today)
print("Tomorrow:", tomorrow)


yesterady: 2024-07-20
today: 2024-07-21
Tomorrow: 2024-07-22


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [32]:

import numpy as np

dts = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

# Printing the dates
print("Dates in July 2016:")
for date in dts:
    print(date)


Dates in July 2016:
2016-07-01
2016-07-02
2016-07-03
2016-07-04
2016-07-05
2016-07-06
2016-07-07
2016-07-08
2016-07-09
2016-07-10
2016-07-11
2016-07-12
2016-07-13
2016-07-14
2016-07-15
2016-07-16
2016-07-17
2016-07-18
2016-07-19
2016-07-20
2016-07-21
2016-07-22
2016-07-23
2016-07-24
2016-07-25
2016-07-26
2016-07-27
2016-07-28
2016-07-29
2016-07-30
2016-07-31


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [34]:

import numpy as np

A = np.array([1, 2, 4, 5])
B = np.array([9, 6, 2, 3])


res1 = A + B
res2 = -A / 2
result = res1 * res2

print("Result :", result)


Result : [ -5.  -8. -12. -20.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
#doubt

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [35]:


import numpy as np


matrix = np.arange(5)  #array values from 0 to 4
matrix = np.tile(matrix, (5, 1))  #repeat 5 timeds

print("5x5 matrix with row values from 0 to 4:")
print(matrix)



5x5 matrix with row values from 0 to 4:
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [37]:
import numpy as np

def generator():
    for i in range(10):
        yield i
#to create a list of integers
int_list = list(generator())

array = np.array(int_list)

print("numpy array from generator:", array)


numpy array from generator: [0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
#will need to ask for logic

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [38]:

import numpy as np

randomm_vector = np.random.rand(10)

#Sorting
sorted_vector = np.sort(randomm_vector)

print("Random vector:", random_vector)
print("Sorted vector:", sorted_vector)


NameError: name 'random_vector' is not defined

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)